name: Test Environment Variables and Secrets

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print Environment Variables and Secrets
        run: |
          echo "Environment Variable (ENV_VAR_1): ${{ env.ENV_VAR_1 }}"
          echo "Secret (ENV_1): ${{ secrets.ENV_1 }}"
          # Avoid exposing secrets directly in logs
          echo "Using the secret: $(echo "${{ secrets.ENV_1 }}" | base64 -d)" > /dev/null
