name: Write Secret to File

on:
  push:
    branches:
      - main

jobs:
  write-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Write secret to file
        run: echo "${{ secrets.MY_SECRET }}" > secret-file.txt
