name: Write Secret to File

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Input Checkout Branch Name'
        required: true
        default: 'master'

jobs:
  write-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Write secret to file
        run: echo "${{ secrets.TEST }}" > secret-file.txt

      - name: Print secret file content
        run: |
          ll
          cat secret-file.txt
