name: Write Secret to File with Approval

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Input Checkout Branch Name'
        required: true
        default: 'master'
      approval:
        description: 'Approve the workflow'
        required: true
        type: boolean

jobs:
  wait_for_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check approval status
        run: |
          if [ "${{ github.event.inputs.approval }}" != "true" ]; then
            echo "Approval not granted. Exiting."
            exit 1
          fi

  write_secret:
    needs: wait_for_approval
    if: ${{ github.event.inputs.approval == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch_name }}

      - name: Write secret to file
        run: echo "${{ secrets.TEST }}" > secret-file.txt

      - name: Print secret file content
        run: |
          ls
          cat secret-file.txt
